<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\commerce_product\Entity\ProductVariationInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function commerce_quantity_increments_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'commerce_product_variation') {
    $fields['qty_increments'] = BaseFieldDefinition::create('decimal')
      ->setLabel(t('Quantity increments'))
      ->setDescription(t('The allowed quantity increments.'))
      ->setRequired(FALSE)
      ->setTranslatable(FALSE)
      ->setSettings([
        'unsigned' => TRUE,
        'size' => 'normal',
        'min' => 0,
      ])
      ->setDefaultValue(1)
      ->setDisplayOptions('view', [
        'type' => 'hidden',
      ])
      ->setDisplayOptions('form', [
        'type' => 'number',
        'weight' => 10,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }
  return $fields;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for commerce_order_item_add_to_cart_form.
 */
function commerce_quantity_increments_form_commerce_order_item_add_to_cart_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['quantity']['widget'][0]['value'])) {
    //$order_item = $form_state->getFormObject()->getEntity();
    //$product_variation = $order_item->getPurchasedEntityId();
    $variation_id = $form['purchased_entity']['widget'][0]['variation']['#value'];
    $product_variation = \Drupal::service('entity_type.manager')->getStorage('commerce_product_variation')->load($variation_id);
    $qty_increments = commerce_quantity_increments_get_increments_from_product_variation($product_variation);
    if ($qty_increments) {
      $form['quantity']['widget'][0]['value']['#element_validate'][] = 'commerce_quantity_increments_add_to_cart_form_validate_qty_increments';
      $form['quantity']['widget'][0]['value']['#default_value'] = $qty_increments;
      $form['quantity']['widget'][0]['value']['#min'] = $qty_increments;
      $form['quantity']['widget'][0]['value']['#step'] = $qty_increments;
    }
  }
}

/**
 * Form element validation callback for quantity field in commerce_order_item_product_variation_add_to_cart_form form.
 */
function commerce_quantity_increments_add_to_cart_form_validate_qty_increments(array &$element, FormStateInterface $form_state, array &$form) {
  $values = $form_state->getValues();
  $variation_id = $values['purchased_entity'][0]['variation'];
  $product_variation = \Drupal::service('entity_type.manager')->getStorage('commerce_product_variation')->load($variation_id);
  $qty_increments = commerce_quantity_increments_get_increments_from_product_variation($product_variation);
  if ($qty_increments) {
    $qty = $values['quantity'][0]['value'];
    if ($qty < $qty_increments || $qty % $qty_increments) {
      $form_state->setError($element, t('This product is available for purchase in increments of @increments only.', ['@increments' => $qty_increments]));
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for views_form_commerce_cart_form_default forms.
 */
function commerce_quantity_increments_form_views_form_commerce_cart_form_default_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $view = reset($form_state->getBuildInfo()['args']);
  if (!empty($view->result) && !empty($form['edit_quantity'])) {
    foreach ($view->result as $row) {
      /** @var \Drupal\commerce_order\Entity\OrderItemInterface $order_item */
      $order_item = $row->_relationship_entities['order_items'];
      $product_variation = $order_item->getPurchasedEntity();
      if ($product_variation instanceof ProductVariationInterface && $qty_increments = commerce_quantity_increments_get_increments_from_product_variation($product_variation)) {
        $form['edit_quantity'][$row->index]['#element_validate'][] = 'commerce_quantity_increments_commerce_cart_form_validate_qty_increments';
        $form['edit_quantity'][$row->index]['#min'] = $qty_increments;
        $form['edit_quantity'][$row->index]['#step'] = $qty_increments;
      }
    }
  }
}

/**
 * Form element validation callback for quantity field in views_form_commerce_cart_form_default forms.
 */
function commerce_quantity_increments_commerce_cart_form_validate_qty_increments(array &$element, FormStateInterface $form_state, array &$form) {
  $values = $form_state->getValues();
  $view = reset($form_state->getBuildInfo()['args']);
  $index = $element['#parents'][1];
  /** @var \Drupal\commerce_order\Entity\OrderItemInterface $order_item */
  $order_item = $view->result[$index]->_relationship_entities['order_items'];
  $product_variation = $order_item->getPurchasedEntity();
  $qty_increments = commerce_quantity_increments_get_increments_from_product_variation($product_variation);
  if ($qty_increments) {
    $qty = $values['edit_quantity'][$index];
    if ($qty < $qty_increments || $qty % $qty_increments) {
      $form_state->setError($element, t('This product is available for purchase in increments of @increments only.', ['@increments' => $qty_increments]));
    }
  }
}

function commerce_quantity_increments_get_increments_from_product_variation(ProductVariationInterface $product_variation) {
  $qty_increments = $product_variation->get('qty_increments')->value;
  if ($qty_increments) {
    if ($qty_increments == round($qty_increments)) {
      // The increments constraint has no fraction, therefore we treat it as an integer.
      $qty_increments = (int)round($qty_increments);
    }
  }
  return $qty_increments;
}

