commerce_payment.commerce_payment_gateway.plugin.alipay_page: &alipay
  type: commerce_payment_gateway_configuration
  mapping:
    dev_notify_domain:
      type: string
      label: 'Development notify domain'
    app_id:
      type: string
      label: 'App ID'
    seller_id:
      type: string
      label: 'Seller ID'
    app_private_key_path:
      type: string
      label: 'App private key path'
    alipay_public_key_path:
      type: string
      label: 'Alipay public key path'
commerce_payment.commerce_payment_gateway.plugin.alipay_app: *alipay
commerce_payment.commerce_payment_gateway.plugin.alipay_wap: *alipay

commerce_payment.commerce_payment_gateway.plugin.wechat_pay_native: &wechat_pay
  type: commerce_payment_gateway_configuration
  mapping:
    dev_notify_domain:
      type: string
      label: 'Development notify domain'
    app_id:
      type: string
      label: 'App ID'
    mch_id:
      type: string
      label: 'Merchant ID'
    key:
      type: string
      label: 'Signature key'
    cert_path:
      type: string
      label: 'Cert path'
    key_path:
      type: string
      label: 'Key path'
commerce_payment.commerce_payment_gateway.plugin.wechat_pay_jsapi: *wechat_pay
commerce_payment.commerce_payment_gateway.plugin.wechat_pay_h5: *wechat_pay
