<?php

/**
 * @file
 * Contains nice_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;

/**
 * Implements hook_help().
 */
function suffix_zx_commerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social module.
    case 'help.page.suffix_zx_commerce':
      $output = '';
      $output .= '<h3>' . t('关于') . '</h3>';
      $output .= '<p>' . t('提供定制化商务流程.') . '</p>';
      return $output;
  }
}


/**
 * Implements hook_preprocess_block().
 */
function suffix_zx_commerce_preprocess_block(array &$variables) {
  // Empty the block local_tasks_block on pages login, reset password
  // and register for removing corresponding tabs on these pages.
  $route_name = \Drupal::routeMatch()->getRouteName();
  echo $route_name;
  echo '<br>';
  echo "plugin_id:".$plugin_id = $variables['elements']['#plugin_id'].'<br>';
  // $routes = ['user.login', 'user.pass', 'user.register'];
  // if (in_array($route_name, $routes) && 'local_tasks_block' === $plugin_id) {
  //   $variables['content'] = [];
  // }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function suffix_zx_commerce_form_user_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ('user.login' == \Drupal::routeMatch()->getRouteName()) {
    echo \Drupal::routeMatch()->getRouteName();
    echo 234234234;
  }

  // Wrap the form.
  $form['#prefix'] = '<div class="wrapper-nice-login login-form">';
  $form['#suffix'] = '</div>';
  $form['#attached']['library'][] = 'nice_login/form';

  // Add reset password link.
  $link = Link::createFromRoute(t('Forgot your password?'), 'user.pass');
  $link->getUrl()->setOption('attributes', ['class' => ['nice-login', 'nice-login-reset-password']]);
  $form['pass']['#prefix'] = '<div class="nice-login-pass">' . $link->toString() . '</div>';

  // Add create account link if user has permission.
  $user_settings = \Drupal::configFactory()->get('user.settings');
  if ($user_settings->get('register') != USER_REGISTER_ADMINISTRATORS_ONLY) {
    $link = Link::createFromRoute(t('Create an account?'), 'user.register');
    $link->getUrl()->setOption('attributes', ['class' => ['nice-login', 'nice-login-create-account']]);
    $form['actions']['submit']['#suffix'] = '<div class="nice-login-create">' . $link->toString() . '</div>';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nice_login_form_user_pass_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ('user.pass' !== \Drupal::routeMatch()->getRouteName()) {
    return;
  }

  // Wrap the form.
  $form['#prefix'] = '<div class="wrapper-nice-login reset-password-form">';
  $form['#suffix'] = '</div>';
  $form['#attached']['library'][] = 'nice_login/form';

  // Add login link.
  $link = Link::createFromRoute(t('Log in'), 'user.login');
  $link->getUrl()->setOption('attributes', ['class' => ['nice-login', 'nice-login-login']]);
  $form['actions']['submit']['#suffix'] = '<div class="nice-login-login">' . $link->toString() . '</div>';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nice_login_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ('user.register' !== \Drupal::routeMatch()->getRouteName()) {
    return;
  }

  // Wrap the form.
  $form['#prefix'] = '<div class="wrapper-nice-login create-account-form">';
  $form['#suffix'] = '</div>';
  $form['#attached']['library'][] = 'nice_login/form';

  // Add login link.
  $link = Link::createFromRoute(t('Log in'), 'user.login');
  $link->getUrl()->setOption('attributes', ['class' => ['nice-login', 'nice-login-login']]);
  $text = t('You have already an account?');
  $form['actions']['submit']['#suffix'] = '<div class="nice-login-login">' . $text . ' ' . $link->toString() . '</div>';
}
