<?php
//use Drupal\Core\Routing\RouteMatchInterface;
//use Drupal\Core\Link;
//
///**
// * Implements hook_form_FORM_ID_alter().
// */
//function nice_login_form_user_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//    if ('user.login' !== \Drupal::routeMatch()->getRouteName()) {
//        echo 324;
//        return;
//    }
//
//    // Wrap the form.
//    $form['#prefix'] = '<div class="wrapper-nice-login login-form">';
//    $form['#suffix'] = '</div>';
//    $form['#attached']['library'][] = 'nice_login/form';
//
//    // Add reset password link.
//    $link = Link::createFromRoute(t('Forgot your password?'), 'user.pass');
//    $link->getUrl()->setOption('attributes', ['class' => ['nice-login', 'nice-login-reset-password']]);
//    $form['pass']['#prefix'] = '<div class="nice-login-pass">' . $link->toString() . '</div>';
//
//    // Add create account link if user has permission.
//    $user_settings = \Drupal::configFactory()->get('user.settings');
//    if ($user_settings->get('register') != USER_REGISTER_ADMINISTRATORS_ONLY) {
//        $link = Link::createFromRoute(t('Create an account?'), 'user.register');
//        $link->getUrl()->setOption('attributes', ['class' => ['nice-login', 'nice-login-create-account']]);
//        $form['actions']['submit']['#suffix'] = '<div class="nice-login-create">' . $link->toString() . '</div>';
//    }
//}


function app_user_commerce_checkout_pane_info_alter(&$definitions) {
    //dump($definitions);exit;
}